export const INPUT_PLACE_NAME_REQUEST  ='INPUT_PLACE_NAME_REQUEST';
export const INPUT_PLACE_NAME_SUCCESS = 'INPUT_PLACE_NAME_SUCCESS';
export const INPUT_PLACE_NAME_FAILURE = 'INPUT_PLACE_NAME_FAILURE';